name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: TestApp

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - uses: microsoft/setup-msbuild@v1.1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m /p:Configuration=Release /p:Platform="${{ matrix.platform }}" ${{ env.SOLUTION_NAME }}.sln
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SOLUTION_NAME }}-${{ matrix.platform }}-${{ github.sha }}
        path: ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release
