name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: ScreenRecorderLib

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: windows-2019
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m '/p:Configuration=Release;Platform="${{ matrix.platform }}"' ${{ env.SOLUTION_NAME }}.sln
    
    - uses: actions/upload-artifact@v3
      with:
        name: ScreenRecorderLib.${{matrix.platform}}
        path: ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.dll
        
  release:
      name: Upload Release
      runs-on: windows-2019
      needs : build
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: ScreenRecorderLib.x86
            path: ScreenRecorderLib.x86.zip
        - uses: actions/download-artifact@v3
          with:
            name: ScreenRecorderLib.x64
            path: ScreenRecorderLib.x64.zip
        - name: Display structure of downloaded files
          run: ls -R
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              .\${{ env.PROJECT_NAME }}\ScreenRecorderLib.x86.zip
              .\${{ env.PROJECT_NAME }}\ScreenRecorderLib.x64.zip
