name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag'  
  push:
    tags:
      - "v*"

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: ScreenRecorderLib

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, x86, ARM64]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - uses: microsoft/setup-msbuild@v1.1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m /p:Configuration=Release /p:Platform="${{ matrix.platform }}" ${{ env.SOLUTION_NAME }}.sln
    
    - uses: actions/upload-artifact@v4
      with:
        name: ScreenRecorderLib.${{matrix.platform}}.zip
        path: |
          ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.dll
          ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.xml
          ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release\ScreenRecorderLib.pdb
        
  release:
      name: Upload Release
      runs-on: ubuntu-latest
      needs : build
      steps:
        - uses: actions/download-artifact@v4
          with:
            path: artifacts/
        - name: Display structure of downloaded files
          run: ls -R
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: artifacts/*.zip
